include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - flutter/*
    - lib/core/injections/injection_container.config.dart


linter:
  rules:
    - prefer_single_quotes
    - cancel_subscriptions
    - avoid_slow_async_io
    - no_logic_in_create_state
    - close_sinks
    - use_string_buffers
    - avoid_returning_null_for_future
    - prefer_void_to_null
    - unnecessary_statements
    - always_require_non_null_named_parameters
    - avoid_returning_null
    - avoid_returning_null_for_void
    - prefer_initializing_formals
    - prefer_typing_uninitialized_variables
    - avoid_annotating_with_dynamic
    - avoid_print
    - control_flow_in_finally
    - constant_identifier_names
    - avoid_relative_lib_imports
    - prefer_if_elements_to_conditional_expressions 
    - annotate_overrides
    - avoid_renaming_method_parameters
    - await_only_futures
    - file_names
    - unnecessary_getters_setters
    - prefer_const_constructors